"""Durable observation and lane-control primitives for parallel coding work."""

from .models import ProcessInfo, ProcessSnapshot
from .invocation import CANONICAL_INVOCATION_SCHEMA, CanonicalInvocation
from .prompt_bundle import PromptBundle, PromptComponent
from .provider import (
    ClaudeCodeProviderAdapter,
    CodexProviderAdapter,
    QwenCodeProviderAdapter,
    ProviderAdapterRegistration,
    ProviderCapabilities,
    ProviderEvidence,
    ProviderHandoff,
    ProviderOperationResult,
    ProviderResumeDecision,
    build_provider_evidence,
    classify_operation,
    decide_resume_or_handoff,
    provider_registry,
    provider_default_command,
    redact_command,
    register_provider_adapter,
    structured_handoff,
    unregister_provider_adapter,
)
from .provider import (
    NOTIFICATION_MODE_SAFE_BOUNDARY_ONLY,
    NOTIFICATION_MODE_WAKE,
    NOTIFICATION_WAKE_TEXT,
    WAKE_TEXT,
    notification_mode,
)
from .profile import RuntimeProfile
from .resume import ResumeAdmission
from .host_adapters import (
    AdapterCapabilities,
    DeliveryCoordinator,
    DeliveryNotice,
    DeliveryReceipt,
    FutureHostFixture,
    HostAdapter,
    HostProfile,
    ManagerEventAck,
)
from .codex_adapter import (
    CodexAdapter,
    SyntheticCodexTransport,
    activate_codex_binding,
    bind_codex_project,
    run_installed_codex_hook,
)
from .claude_installer import activate_claude_binding, bind_claude_project
from .qwen_adapter import QwenAdapter, SyntheticQwenTransport
from .qwen_installer import (
    activate_qwen_binding,
    bind_qwen_project,
    check_qwen_adapter,
    install_qwen_adapter,
    run_installed_qwen_hook,
    uninstall_qwen_adapter,
    upgrade_qwen_adapter,
)
from .lane_lifecycle import ImmutableSourceView, RetirementResult
__all__ = [
    "CANONICAL_INVOCATION_SCHEMA",
    "CanonicalInvocation",
    "ClaudeCodeProviderAdapter",
    "CodexProviderAdapter",
    "QwenCodeProviderAdapter",
    "NOTIFICATION_MODE_SAFE_BOUNDARY_ONLY",
    "NOTIFICATION_MODE_WAKE",
    "NOTIFICATION_WAKE_TEXT",
    "ProviderAdapterRegistration",
    "ProviderCapabilities",
    "ProviderEvidence",
    "ProviderHandoff",
    "ProviderOperationResult",
    "ProviderResumeDecision",
    "WAKE_TEXT",
    "build_provider_evidence",
    "notification_mode",
    "classify_operation",
    "decide_resume_or_handoff",
    "provider_registry",
    "provider_default_command",
    "redact_command",
    "register_provider_adapter",
    "structured_handoff",
    "unregister_provider_adapter",
    "ProcessInfo",
    "ProcessSnapshot",
    "PromptBundle",
    "PromptComponent",
    "ResumeAdmission",
    "RuntimeProfile",
    "AdapterCapabilities",
    "CodexAdapter",
    "QwenAdapter",
    "activate_codex_binding",
    "bind_codex_project",
    "activate_claude_binding",
    "bind_claude_project",
    "activate_qwen_binding",
    "bind_qwen_project",
    "DeliveryCoordinator",
    "DeliveryNotice",
    "DeliveryReceipt",
    "FutureHostFixture",
    "HostAdapter",
    "HostProfile",
    "ImmutableSourceView",
    "ManagerEventAck",
    "RetirementResult",
    "run_installed_codex_hook",
    "check_qwen_adapter",
    "install_qwen_adapter",
    "run_installed_qwen_hook",
    "SyntheticCodexTransport",
    "SyntheticQwenTransport",
    "uninstall_qwen_adapter",
    "upgrade_qwen_adapter",
]
__version__ = "0.1.0"
