"""Durable observation and lane-control primitives for parallel coding work."""

from .models import ProcessInfo, ProcessSnapshot
from .invocation import CANONICAL_INVOCATION_SCHEMA, CanonicalInvocation
from .prompt_bundle import PromptBundle, PromptComponent
from .provider import (
    ClaudeCodeProviderAdapter,
    CodexProviderAdapter,
    ProviderAdapterRegistration,
    ProviderCapabilities,
    ProviderEvidence,
    ProviderHandoff,
    ProviderOperationResult,
    ProviderResumeDecision,
    build_provider_evidence,
    classify_operation,
    decide_resume_or_handoff,
    provider_registry,
    redact_command,
    register_provider_adapter,
    structured_handoff,
    unregister_provider_adapter,
)
from .provider import (
    NOTIFICATION_MODE_SAFE_BOUNDARY_ONLY,
    NOTIFICATION_MODE_WAKE,
    NOTIFICATION_WAKE_TEXT,
    WAKE_TEXT,
    notification_mode,
)
from .profile import RuntimeProfile
from .resume import ResumeAdmission
from .host_adapters import (
    AdapterCapabilities,
    DeliveryCoordinator,
    DeliveryNotice,
    DeliveryReceipt,
    FutureHostFixture,
    HostAdapter,
    HostProfile,
    ManagerEventAck,
)
from .codex_adapter import (
    CodexAdapter,
    SyntheticCodexTransport,
    activate_codex_binding,
    bind_codex_project,
    run_installed_codex_hook,
)
from .lane_lifecycle import ImmutableSourceView, RetirementResult
from .capability_broker import (
    AdapterResult,
    CapabilityAdapter,
    CapabilityAdapterError,
    CapabilityAdapterUnavailable,
    CapabilityApproval,
    CapabilityBroker,
    CapabilityDenied,
    CapabilityError,
    CapabilityPermit,
    CapabilityRequest,
    CapabilityResult,
    CapabilitySnapshot,
    CleanupEvidence,
    FakeCapabilityAdapter,
)
from .firmware_campaign import FirmwareAction, FirmwareCampaignPack, FirmwareOperation
from .firmware_adapter import FirmwareHardwareAdapter, HardwareCapabilityAdapter

__all__ = [
    "CANONICAL_INVOCATION_SCHEMA",
    "CanonicalInvocation",
    "ClaudeCodeProviderAdapter",
    "CodexProviderAdapter",
    "NOTIFICATION_MODE_SAFE_BOUNDARY_ONLY",
    "NOTIFICATION_MODE_WAKE",
    "NOTIFICATION_WAKE_TEXT",
    "ProviderAdapterRegistration",
    "ProviderCapabilities",
    "ProviderEvidence",
    "ProviderHandoff",
    "ProviderOperationResult",
    "ProviderResumeDecision",
    "WAKE_TEXT",
    "build_provider_evidence",
    "notification_mode",
    "classify_operation",
    "decide_resume_or_handoff",
    "provider_registry",
    "redact_command",
    "register_provider_adapter",
    "structured_handoff",
    "unregister_provider_adapter",
    "ProcessInfo",
    "ProcessSnapshot",
    "PromptBundle",
    "PromptComponent",
    "ResumeAdmission",
    "RuntimeProfile",
    "AdapterCapabilities",
    "CodexAdapter",
    "activate_codex_binding",
    "bind_codex_project",
    "DeliveryCoordinator",
    "DeliveryNotice",
    "DeliveryReceipt",
    "FutureHostFixture",
    "HostAdapter",
    "HostProfile",
    "ImmutableSourceView",
    "ManagerEventAck",
    "RetirementResult",
    "AdapterResult",
    "CapabilityAdapter",
    "CapabilityAdapterError",
    "CapabilityAdapterUnavailable",
    "CapabilityApproval",
    "CapabilityBroker",
    "CapabilityDenied",
    "CapabilityError",
    "CapabilityPermit",
    "CapabilityRequest",
    "CapabilityResult",
    "CapabilitySnapshot",
    "CleanupEvidence",
    "FakeCapabilityAdapter",
    "FirmwareAction",
    "FirmwareCampaignPack",
    "FirmwareHardwareAdapter",
    "FirmwareOperation",
    "HardwareCapabilityAdapter",
    "run_installed_codex_hook",
    "SyntheticCodexTransport",
]
__version__ = "0.1.0"
